//USEUNIT add_a_new_user
//USEUNIT add_new_client
//USEUNIT add_treatment_location
//USEUNIT edit_client_details
//USEUNIT edit_client_location
//USEUNIT edit_client_location_licenses
//USEUNIT update_a_location_admin
//USEUNIT update_a_user
//USEUNIT add_a_banner_message
//USEUNIT add_inrstar_feedback
//USEUNIT log_off_admin_dash
//USEUNIT login_admin_dash
//USEUNIT validate_login